language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=fibonacci.coverprofile ./fibonacci
  - go test -coverprofile=math.coverprofile ./math
  - go test -coverprofile=parenthesis.coverprofile ./parenthesis
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
